#ifndef CPPTCL_VERSION_H
#define CPPTCL_VERSION_H

// Variables are autogenerated and compiled
// into the library by cmake
extern "C" {
    extern const char* CPPTCL_GIT_HASH;
    extern const char* CPPTCL_GIT_BRANCH;
}

const char* cpptcl_git_hash() {
    return CPPTCL_GIT_HASH;
}

const char* cpptcl_git_branch() {
    return CPPTCL_GIT_BRANCH;
}

#endif //CPPTCL_VERSION_H
