name: Mac CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew update
        brew install tcl-tk || true
        ls -l /usr/local/opt/tcl-tk/include/tcl-tk
        sudo mkdir -p /usr/local
        sudo ln -sf /usr/local/opt/tcl-tk/include/tcl-tk /usr/local/include/tcl8.6
        sudo install /usr/local/opt/tcl-tk/lib/libtcl* /usr/local/lib
        sudo ln -sf /usr/local/opt/tcl-tk/bin/tclsh8.6 /usr/local/bin/tclsh
        sudo ln -sf /usr/local/opt/tcl-tk/bin/tclsh8.6 /usr/local/bin/tclsh8.6
    - name: make
      run: make
    - name: install
      run: sudo make install
    - name: make test
      run: make test
    - name: make examples
      run: make examples
